spring:
  # database Setting
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  prefix: ${JWT_PREFIX}
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET}
  access-expire-time: ${JWT_ACCESS_TIME}
  refresh-expire-time: ${JWT_REFRESH_TIME}