spring:
  # database Setting
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

cloud:
  aws:
    bucket-name: ${AWS_BUCKET_NAME}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

jwt:
  prefix: ${JWT_PREFIX}
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET}
  access-expire-time: ${JWT_ACCESS_TIME}
  refresh-expire-time: ${JWT_REFRESH_TIME}